spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  main:
    allow-bean-definition-overriding: true

logging:
  level:
    org.hibernate.type.descriptor.sql: trace
