spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/batch-db?zeroDateTimeBehavior=convertToNull&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: seungsu
    password: 1111
    hikari:
      maximum-pool-size: 20
    driver-class-name: com.mysql.cj.jdbc.Driver

  batch:
    jdbc:
      initialize-schema: always

server:
  port: 8000